### ISSUE TITLE
Навести порядок в разделах dependencies/devDependencies

### ISSUE THREAD

**Issue by codyfet** [TimmyGOGO/office_map_experiments#1]
нужно разделить зависимости для продакшн сборки (dependencies) и дев сборки (devDependencies).
например, react должен войти в dependencies, а webpack в devDependencies.

также необходимо создать npm run build команду (то есть добавить в раздел scripts команду build). Здесь как раз и будет запускаться webpack --mode production который соберет твои dependencies (и только их) 

лишние зависимости нужно удалить (будет не лишним выполнить команду npm prune).

**Comment by TimmyGOGO** [comment]
1. Зависимости раздедил в соответствиями с отредактированными правилами из eslint-config-airbnb
2. Скрипт build написан, создаёт выходные файлы в папке dist/
3. npm prune запускал - все в норме
4. Удалены лишние зависимости
