### ISSUE TITLE
Настроить ESLint

### ISSUE THREAD

**Issue by codyfet** [TimmyGOGO/office_map_experiments#2]
Это позволит настроить правила по стилю кода и т.д.

Код будет удобнее читать. Советую не использовать сразу готовые наборы, а добавлять по одному правилу (лишние строки в коде, пробелы в конструкциях if (...) {} и т.д.) - последовательно.  Так лучше прочувствуешь процесс. В любом случае - с настройкой - поможем.

**Comment by TimmyGOGO** [comment]
ESLint настроен. Правильно ли - вопрос. Воспользовался готовой сборкой и скриптами отсюда:
https://habr.com/ru/company/ruvds/blog/428173/

Однако, получилась не прямая копия, например: Husky, Lint-Staged и EditorConfig я вообще не добавлял. Правила для eslint пришлось дополнить:
'import/no-unresolved': 'off' <- жаловался на import
'object-shorthand': [0, 'never'] <- правило использовалось по умолчанию, для след. случая: 
  если у нам нужно определить объект: let obj = {id: id}; то лучше писать: let obj = {id}; 
Но мне кажется, что если мы определяем много свойств у объекта, то это визуально выглядит не очень:
const newObject = {
    category: type,
    id,
    coordinates: coords,
    movable: true,
    correctLocation: true,
    color: TABLE_COLOR
};

**Comment by TimmyGOGO** [comment]
Сделано. Правила настроены по стандарту airbnb с собственными правками. Все правки обсудили.
